### ISSUE TITLE
Cannot check only for upgrade

### ISSUE THREAD

**Issue by Krakinou** [YunoHost/package_check#59]
- Create a check_process file with '0' for all tests except for `upgrade=1` :
=> Test will fail with message:
`Error: yunohost cli - Argument 'path' is required`
- if `setup_sub_dir=1`, then the check will be correctly performed.

**Comment by maniackcrudelis** [comment]
Please try this testing https://github.com/YunoHost/package_check/pull/60

**Comment by Krakinou** [comment]
It worked.
However, I noticed another unwanted behavior with the upgrade check.
If you have multiple "upgrade from commit" in the check_process file and you set only one of them to 1, all the commit will be tested nevertheless

**Comment by maniackcrudelis** [comment]
Good catch!
I'm working today on Package check, I'll have a look to it

**Comment by maniackcrudelis** [comment]
I tried with 2 upgrade from commit, it worked as expected.
I could tried with one or the other without problem.
But it was after many fixes into the code. Maybe I fixed it without noticing.

**Comment by Krakinou** [comment]
Hmm, even with the last testing of package_check, I still have the issue. 
Can you try run it for 
https://github.com/YunoHost-Apps/emailpoubelle_ynh/tree/package_check
It will still run the upgrade for the same version even if it's set to 0, exerpt from the log:
````
>> Upgrade from the same version... [Test 3/2]

Preliminary install...
Uses an existing snapshot for sub path installation.
Working time: 1 second.

Upgrade...
Start the LXC container.
Create witness files...
Working time: 8 seconds.
Working time: 9 seconds.
Upgrade successful. (0)
Info: yunohost.app app_upgrade - [919.1] Now upgrading app emailpoubelle…
Warning: yunohost.hook <lambda> - [919.1] Upgrade forced for package check.
Info: yunohost.backup _collect_app_files - [1061.1] Collecting files to be backuped for emailpoubelle…
Info:  [....................] > Loading installation settings... [00h00m,00s]
Info:  [##..................] > Backing up the main app directory... [00h00m,00s]
Info:  [#####...............] > Backing up nginx web server configuration... [00h00m,00s]
Info:  [########............] > Backing up the MySQL database... [00h00m,00s]
Info:  [###########.........] > Backing up cron configuration... [00h00m,00s]
Info:  [##############......] > Backing up postfix conf configuration... [00h00m,00s]
Info: yunohost.backup backup_create - [1061.1] Now creating a backup archive from the files collected…
Info:  Upgrading nginx web server configuration...
Info:  Reload the service nginx
Info:  Installing dependencies
Info:  Downloading sources to /var/www/emailpoubelle
Info:  Restart the service php7.0-fpm
Info:  Reload the service nginx
Info:  Reload the service postfix
````
The upgrade will fail, but it's normal I'm working on it.

The behavior of package_check has changed since yesterday as I'm forced to set an install before trying an upgrade, which I'm not sure it make sense as the upgrade is done from a previous version?

**Comment by maniackcrudelis** [comment]
That's not the correct commit https://github.com/YunoHost-Apps/emailpoubelle_ynh/blob/package_check/check_process#L28

**Comment by Krakinou** [comment]
Sure, typo corrected, but still 3/2 tests run by package_check :)

**Comment by maniackcrudelis** [comment]
OK, I do reproduce your error.
I'll have a look to it.

**Comment by alexAubin** [comment]
Closing because probably fixed since then
